# Start from a base Docker distribution (Ubuntu 18.04)
FROM ros:melodic-robot-bionic

RUN apt-get update && \
    # Install a whole bunch of dependencies
    apt-get -y --no-install-recommends install build-essential cmake git libgtk-3-dev vim \
    pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev curl && \
    apt-get -y autoremove && \
    apt-get -y clean

# Download and install CLion
RUN curl -L "https://download.jetbrains.com/cpp/CLion-2019.2.5.tar.gz" -o /etc/clion.tar.gz && \
    tar -xzf /etc/clion.tar.gz --directory /etc && \
    ln -s /etc/clion-2019.2.5/bin/clion.sh /etc/clion-2019.2.5/bin/clion && \
    rm -rf /etc/clion.tar.gz
ENV PATH="/etc/clion-2019.2.5/bin:${PATH}"

# Build and install OpenCV
RUN mkdir /tmp/opencv && \
    git clone https://github.com/opencv/opencv.git /tmp/opencv/core && \
    git clone https://github.com/opencv/opencv_contrib.git /tmp/opencv/contrib && \
    cd /tmp/opencv/core && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=RELEASE -DINSTALL_C_EXAMPLES=OFF -DWITH_TBB=ON -DWITH_V4L=ON \
          -DWITH_QT=OFF -DWITH_OPENGL=OFF -DOPENCV_EXTRA_MODULES_PATH=../../contrib/modules \
          -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF \
          -DBUILD_opencv_apps=OFF -DBUILD_openev_legacy=OFF -DBUILD_opencv_python2=OFF \
          -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DWITH_OPENMP=ON -DWITH_IPP=ON -DWITH_CSTRIPES=ON \
          -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_FLAGS="-DTBB_USE_GCC_BUILTINS=1"  \
	      -DOPENCV_ENABLE_NONFREE=ON .. && \
    # Compile with max number of cores
    make -j$(nproc --ignore=1) && \
    make install && \
    rm -rf /tmp/*

# Setup bash entry point
COPY ./entrypoint.dev /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh

# Setup permissions
RUN (echo "root:followbot" | chpasswd) && \
    useradd -ms /bin/bash developer && \
    (echo "developer:password" | chpasswd)
USER developer
WORKDIR /home/developer

# Git clone the repo and update ROS dependencies
RUN cd /home/developer && \
    git clone https://github.com/thearchitector/followbot.git && \
    rosdep update

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
